### ISSUE TITLE
OpenBCIRx async start() 

### ISSUE THREAD

**Issue by JayKan** [NeuroJS/openbci-rx#14]
@alexcastillo,

When running `npm start`, I was getting syntax errors that relates `async start()` locally. However, when I created a brand new node project and install `openbci-rx` as its dependencies and run, everything is working as expected. Please find attached screenshot for the detailed error:

![screen shot 2017-04-03 at 4 25 24 pm](https://cloud.githubusercontent.com/assets/1400300/24635720/19b57d8c-188a-11e7-80c5-a34318c927b6.png)

It would be great if you can run via the example demos locally, maybe there are additional steps that I'm not aware in order to run examples locally, please let me know!

**Comment by alexcastillo** [comment]
Hey Jay,

async/await is only available in node v7+
What node version are you running?

**Comment by JayKan** [comment]
@alexcastillo,

I was running on node 6.5. Let me get back to you once I've tested on node v7+.

**Comment by JayKan** [comment]
@alexcastillo,

Apparently, only node 7.6.0 >= supports async/await functionality. I've tried node 7.2 - 7.5 and I was getting the similar error. However, once I've upgraded my node to 7.6.0 >=, there isn't any issue running `npm start`.

Should I add a prerequisites section on README to indicate that you must use node version >= 7.6 under development, and a `.nvmrc` file to lock the node version for local development? I think this will avoid any issues when new community members try to contribute. Let me know what you think!

**Comment by alexcastillo** [comment]
Sure, feel free to submit a PR with those updates. Would also recommend adding "engines" in package.json.

https://docs.npmjs.com/files/package.json#engines

**Comment by alexcastillo** [comment]
See commit #577b4a29548ac7d72da0b9b746a837dc6c7ef695

**Comment by JayKan** [comment]
@alexcastillo,

That's good to know. With adding `engines` property on package.json, I don't think we will need a `.nvmrc` file. Anyways I will send a PR to update the README :)
