### ISSUE TITLE
Tracking: Ganglion support

### ISSUE THREAD

**Issue by aj-ptw** [NeuroJS/openbci-rx#2]
How do we add in Ganglion support here?

https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion

**Comment by alexcastillo** [comment]
Hey @aj-ptw,

I don't know anything about Ganglion yet, but I would like to support it.
Let's set up a meeting and talk how it is different and why there is a separate library for it.

**Comment by alexcastillo** [comment]
@aj-ptw I've added Ganglion support.
Only remaining issue: https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion/issues/30
